// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PillDispenser.proto

package assign3.grpc;

public interface DownloadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assign3.grpc.DownloadReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patientId = 1;</code>
   */
  int getPatientId();
}
