// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PillDispenser.proto

package com.example.springdemo.grpc;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assign3.grpc.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
