// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PillDispenser.proto

package com.example.springdemo.grpc;

public interface MedicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assign3.grpc.Medication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 medicationId = 1;</code>
   */
  int getMedicationId();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string intakeInterval = 3;</code>
   */
  String getIntakeInterval();
  /**
   * <code>string intakeInterval = 3;</code>
   */
  com.google.protobuf.ByteString
      getIntakeIntervalBytes();
}
