// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PillDispenser.proto

package com.example.springdemo.grpc;

public interface MedPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assign3.grpc.MedPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .assign3.grpc.Medication medication = 1;</code>
   */
  java.util.List<Medication>
      getMedicationList();
  /**
   * <code>repeated .assign3.grpc.Medication medication = 1;</code>
   */
  Medication getMedication(int index);
  /**
   * <code>repeated .assign3.grpc.Medication medication = 1;</code>
   */
  int getMedicationCount();
  /**
   * <code>repeated .assign3.grpc.Medication medication = 1;</code>
   */
  java.util.List<? extends MedicationOrBuilder>
      getMedicationOrBuilderList();
  /**
   * <code>repeated .assign3.grpc.Medication medication = 1;</code>
   */
  MedicationOrBuilder getMedicationOrBuilder(
          int index);
}
