FROM openjdk:8
ADD target/project-assig1.jar project-assig1.jar
EXPOSE 8080
#ENTRYPOINT ["java", "-jar", "project-assig1.jar"]
ENTRYPOINT ["java", "-jar","project-assig1.jar"]

#FROM openjdk:8
#ADD target/project-assig1.jar project-assig1.jar
#ADD src/main/resources/wrapper.sh wrapper.sh
#RUN bash -c 'touch /project-assig1.war'
#RUN bash -c 'chmod +x /wrapper.sh'
#ENTRYPOINT["/bin/sh", "/wrapper.sh"]
